# Generated by Django 4.2.7 on 2024-01-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
