# Generated by Django 4.2.7 on 2024-01-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_match_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="user_matches_played",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="opponent_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="result",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="user_elo",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="user_elo_delta",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="user_expected_result",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="user_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="user_win_rate",
            field=models.FloatField(null=True),
        ),
    ]
