# Generated by Django 4.2.7 on 2024-02-21 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_match_user_friends_alter_match_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="user_friends",
        ),
        migrations.CreateModel(
            name="FriendsHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friends_history_user",
                        to="api.user",
                    ),
                ),
            ],
        ),
    ]
