# Generated by Django 4.2.7 on 2024-02-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth',
            field=models.BooleanField(default=False),
        ),
    ]
