# Generated by Django 4.2.7 on 2024-03-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_oauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_from_auth_service',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='oauth',
            field=models.CharField(choices=[(None, 'None'), ('github', 'github'), ('42api', '42api')], default=None, max_length=7, null=True),
        ),
    ]
