# Generated by Django 4.2.7 on 2024-01-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_forgotpasswordcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_state', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
