# Generated by Django 4.2.7 on 2024-03-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_id_from_auth_service_alter_user_oauth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_from_auth_service',
            new_name='id_from_42api',
        ),
        migrations.AddField(
            model_name='user',
            name='id_from_github',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
