# Generated by Django 4.2.7 on 2024-01-22 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_pendingoauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingoauth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
