# Generated by Django 4.2.7 on 2024-03-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_id_from_auth_service_user_id_from_42api_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='oauth',
        ),
        migrations.AddField(
            model_name='user',
            name='oauth_42api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='oauth_github',
            field=models.BooleanField(default=False),
        ),
    ]
