# Generated by Django 4.2.7 on 2024-03-01 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_oauth_user_oauth_42api_user_oauth_github'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.CreateModel(
            name='UserOAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('github', 'github'), ('42api', '42api')], max_length=20)),
                ('service_id', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oauth', to='user.user')),
            ],
            options={
                'verbose_name': 'User OAuth',
                'verbose_name_plural': 'User OAuths',
            },
        ),
    ]
