# Generated by Django 4.2.7 on 2024-02-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_avatar_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingoauth',
            name='source',
            field=models.CharField(default='asdafa', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='forgotPasswordCode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
