# Generated by Django 4.2.7 on 2024-03-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_options_useroauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_from_42api',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_from_github',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oauth_42api',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oauth_github',
        ),
    ]
