# Generated by Django 4.2.7 on 2024-02-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_pendingoauth_source_alter_user_forgotpasswordcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='elo',
        ),
    ]
