# Generated by Django 4.2.7 on 2024-02-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_has_2fa_user_totp_config_url_user_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
