# Generated by Django 4.2.7 on 2024-02-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_secret_key',
        ),
    ]
