# Generated by Django 4.2.7 on 2024-02-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_elo'),
        ('user', '0008_user_has_2fa_user_totp_config_url_user_totp_secret'),
    ]

    operations = [
    ]
