# Generated by Django 4.2.7 on 2024-02-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
