# Generated by Django 4.2.7 on 2024-02-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pendingoauth',
            name='hashed_state',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
