# Generated by Django 4.2.7 on 2024-02-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_account_deleted_alter_pendingoauth_hashed_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailVerificationToken',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emailVerificationTokenExpiration',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emailVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
