# Generated by Django 4.2.7 on 2024-02-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_has_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_config_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
