# Generated by Django 4.2.7 on 2024-02-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_last_activity_alter_user_password'),
        ('user', '0013_user_last_login'),
    ]

    operations = [
    ]
