USER_STATS_CONNECT_ERROR = 'Could not connect to user-stats'
USER_STATS_ELO_ERROR = 'Could not get user\'s elo'
GAME_CREATOR_CONNECT_ERROR = 'Could not connect to game-creator'
GAME_CREATOR_CREATE_GAME_ERROR = 'Could not create game'
ALREADY_IN_QUEUE = 'User is already in the queue'
ALREADY_IN_GAME_ERROR = 'User is already in the game'
