USER_STATS_CONNECT_ERROR = 'could not connect to user-stats'
USER_STATS_ELO_ERROR = 'could not get user\'s elo'
GAME_CREATOR_CONNECT_ERROR = 'could not connect to game-creator'
GAME_CREATOR_CREATE_GAME_ERROR = 'could not create game'
ALREADY_IN_QUEUE = 'user is already in queue'
ALREADY_IN_GAME_ERROR = 'user is already in the game'
