services:

    front-nginx:
        networks:
            - transcendence
            - front
        build:
            context: nginx
            dockerfile: Dockerfile
        ports:
            - "443:443"
        depends_on:
            - front-vite
        volumes:
            - front_dist:/transcendence/
            - ssl_certs:/etc/nginx/ssl

    front-vite:
        image: node:21-bookworm
        networks:
            - front
        working_dir: /app
        volumes:
            - front_code:/app
        command: sh -c "npm install && npm run build"
        restart: on-failure
