services:

    front-nginx:
        networks:
            - transcendence
            - front
        build:
            context: nginx
            dockerfile: Dockerfile
        ports:
            - "443:443"
        depends_on:
            notification:
                condition: service_healthy
            tournament-nginx:
                condition: service_healthy
            user-management-nginx:
                condition: service_healthy
            pong-server-nginx:
                condition: service_healthy
            user-stats-nginx:
                condition: service_healthy
            front-vite:
                condition: service_completed_successfully
        volumes:
            - front_dist_volume:/transcendence/
            - ssl_certs:/etc/nginx/ssl

    front-vite:
        image: node:21-bookworm
        networks:
            - front
        working_dir: /app
        volumes:
            - front_code:/app
            - front_dist_volume:/app/dist
        command: sh -c "npm install && npm run build"
        restart: on-failure
