# Generated by Django 4.2.7 on 2023-12-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tournament_is_private_tournament_max_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
