# Generated by Django 4.2.7 on 2023-12-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tournament_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='admin_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
