# Generated by Django 4.2.7 on 2024-01-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_player_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
