# Generated by Django 4.2.7 on 2024-01-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_match_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
