# Generated by Django 4.2.7 on 2024-01-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_match_player_1_score_match_player_2_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
