# Generated by Django 4.2.7 on 2024-02-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_match_player_1_alter_match_player_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='registration_deadline',
        ),
    ]
