# Generated by Django 4.2.7 on 2024-02-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_tournament_registration_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
