version: '3'

name: transcendence

services:
    # Front
    front-nginx:
        extends:
            file: front/docker/docker-compose.yaml
            service: front-nginx

    front-vite:
        extends:
            file: front/docker/docker-compose.yaml
            service: front-vite

    # User management
    user-management:
        extends:
            file: user_management/docker/docker-compose.yaml
            service: user-management
    user-management-db:
        extends:
            file: user_management/docker/docker-compose.yaml
            service: user-management-db
    user-management-nginx:
        extends:
            file: user_management/docker/docker-compose.yaml
            service: user-management-nginx

    # Matchmaking
    matchmaking:
        extends:
            file: matchmaking/docker/docker-compose.yaml
            service: matchmaking

    # Tournament
    tournament:
        extends:
            file: tournament/docker/docker-compose.yaml
            service: tournament
    tournament-db:
        extends:
            file: tournament/docker/docker-compose.yaml
            service: tournament-db
    tournament-nginx:
        extends:
            file: tournament/docker/docker-compose.yaml
            service: tournament-nginx

    # Server Side Pong
    pong-server:
        extends:
            file: pong_server/docker/docker-compose.yaml
            service: pong-server


networks:
    front:
        driver: bridge

    user_management:
        driver: bridge

    tournament:
        driver: bridge

    transcendence:
        driver: bridge


volumes:
    # Front
    front_code:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: front/app/

    front_dist:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: front/app/dist/

    # User management
    user_management_postgres_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: user_management/docker/volumes/db/
    user_management_code:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: user_management/src/
    user_management_static_volume:
    user_management_media_volume:

    # Matchmaking
    matchmaking_code:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: matchmaking/src/

    # Tournament
    tournament_postgres_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: tournament/docker/volumes/db/
    tournament_code:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: tournament/src/
    tournament_static_volume:
    tournament_media_volume:

    # Server Side Pong
    pong_server_code:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: pong_server/src/

    # Common code
    common_code:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: common
