services:
    front-nginx:
      networks:
          - front
          - transcendence
      build:
        context: nginx
        dockerfile: Dockerfile
      ports:
          - "80:80"
          - "443:443"
      depends_on:
          - front
      volumes:
          - front_static_volume:/app/static
          - front_media_volume:/app/media
      restart: on-failure


    front:
      networks:
          - front
      build:
          context: .
          dockerfile: Dockerfile
      command: gunicorn front.wsgi:application -w 4 -b 0.0.0.0:8000
      volumes:
          - front_code:/app/front/
      expose:
          - "8000"
      depends_on:
          - front-db
      restart: on-failure

    front-db:
        networks:
            - front
        image: postgres:16.0-bookworm
        environment:
            POSTGRES_DB: mydatabase
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
        volumes:
            - front_postgres_volume:/var/lib/postgresql/data
        restart: on-failure
