services:
    matchmaking:
        networks:
            - transcendence
        build:
            context: .
            dockerfile: Dockerfile
        command: python -m src.matchmaking
        volumes:
            - matchmaking_code:/app/src/
        expose:
            - "3000"
        ports:
            - "6000:3000"
        restart: on-failure
