services:
    pong-server:
        networks:
            - transcendence
        build:
            context: .
            dockerfile: Dockerfile
        command: python3 /app/src/main.py
        volumes:
            - pong_server_code:/app/src/
        expose:
            - "4242"
        restart: on-failure
