services:

    pong-server-nginx:
        networks:
            - transcendence
            - pong_server
        expose:
            - "443"
        ports:
            - "${PONG_GAME_CREATOR_NGINX_PORT}:443"
        build:
            context: nginx
            dockerfile: Dockerfile
        volumes:
            - ssl_certs:/etc/nginx/ssl
        depends_on:
            pong-server:
                condition: service_healthy
        healthcheck:
            test: [ "CMD-SHELL", "curl -kf https://localhost/health/" ]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: on-failure

    pong-server:
        networks:
            - transcendence
            - pong_server
        ports:
            - '${PONG_GAME_SERVERS_MIN_PORT}-${PONG_GAME_SERVERS_MAX_PORT}:${PONG_GAME_SERVERS_MIN_PORT}-${PONG_GAME_SERVERS_MAX_PORT}'
        expose:
            - "8000"
        build:
            args:
                - GAME_SERVER_PATH=/app/src/game_server/
                - PONG_GAME_SERVERS_MIN_PORT=${PONG_GAME_SERVERS_MIN_PORT}
                - PONG_GAME_SERVERS_MAX_PORT=${PONG_GAME_SERVERS_MAX_PORT}
                - PATH_TO_SSL_CERTS=/app/ssl/
            context: .
            dockerfile: Dockerfile
        volumes:
            - pong_server_code:/app/pong_server_code/
            - ssl_certs:/app/ssl
            - common_code:/app/common
        command: /app/run.sh
        depends_on:
            pong-server-cache:
                condition: service_healthy
        healthcheck:
            test: [ "CMD-SHELL", "curl -kf https://localhost:8000/health/" ]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: on-failure

    pong-server-cache:
        networks:
            - pong_server
        image: redis:7.2.4-bookworm
        healthcheck:
            test: [ "CMD-SHELL", "redis-cli", "--raw", "INCR", "ping" ]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: on-failure
