services:
    tournament-nginx:
        networks:
            - transcendence
            - tournament
        build:
            context: nginx
            dockerfile: Dockerfile
        expose:
            - "443"
        ports:
            - "6001:443"
        volumes:
            - ssl_certs:/etc/nginx/ssl
        healthcheck:
            test: [ "CMD-SHELL", "curl -kf https://localhost/health/" ]
            interval: 5s
            timeout: 5s
            retries: 60
        restart: on-failure

    tournament:
        networks:
            - transcendence
            - tournament
        build:
            context: .
            dockerfile: Dockerfile
        command: sh -c "cp -r /app/tournament /app/src &&
                        cp /app/tournament/.env /app/src/.env &&
                        rm -rf /app/src/common &&
                        cp -r /app/common /app/src/common &&
                        pip install --root-user-action=ignore --no-cache-dir -r /app/src/common/docker/requirements.txt &&
                        python3 src/manage.py makemigrations &&
                        python3 src/manage.py migrate &&
                        gunicorn -c /app/gunicorn.conf.py"
        volumes:
            - tournament_code:/app/tournament
            - common_code:/app/common
            - ssl_certs:/app/ssl
        expose:
            - "8000"
        healthcheck:
            test: [ "CMD-SHELL", "curl -kf https://localhost:8000/health/" ]
            interval: 5s
            timeout: 5s
            retries: 60
        restart: on-failure

    tournament-db:
        networks:
            - tournament
        build:
            context: postgres
            dockerfile: Dockerfile
        volumes:
            - tournament_postgres_volume:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: $TOURNAMENT_DB_NAME
            POSTGRES_USER: $TOURNAMENT_DB_USER
            POSTGRES_PASSWORD: $TOURNAMENT_DB_PASSWORD
        healthcheck:
            test: ["CMD-SHELL", "healthcheck.sh"]
            interval: 5s
            timeout: 5s
            retries: 60
        restart: on-failure
