services:
    tournament-nginx:
        networks:
            - transcendence
            - tournament
        build:
            context: nginx
            dockerfile: Dockerfile
        expose:
            - "443"
        ports:
            - "6001:443"
        volumes:
            - tournament_static_volume:/app/static
            - tournament_media_volume:/app/media
            - ssl_certs:/etc/nginx/ssl
        healthcheck:
            test: [ "CMD-SHELL", "curl -kf https://localhost/health/" ]
            interval: 5s
            timeout: 5s
            retries: 5
        depends_on:
            tournament:
                condition: service_healthy
        restart: on-failure

    tournament:
        networks:
            - transcendence
            - tournament
        build:
            context: .
            dockerfile: Dockerfile
        command: sh -c "cp -r /app/tournament /app/src &&
                        cp -r /app/common /app/src/common &&
                        pip install --root-user-action=ignore --no-cache-dir -r /app/src/common/docker/requirements.txt &&
                        python3 src/manage.py makemigrations &&
                        python3 src/manage.py migrate &&
                        gunicorn -c /app/gunicorn.conf.py"
        volumes:
            - tournament_code:/app/tournament
            - common_code:/app/common
            - ssl_certs:/app/ssl
        expose:
            - "8000"
        healthcheck:
            test: [ "CMD-SHELL", "curl -kf https://localhost:8000/health/" ]
            interval: 5s
            timeout: 5s
            retries: 5
        depends_on:
            tournament-db:
                condition: service_healthy
        restart: on-failure

    tournament-db:
        networks:
            - tournament
        image: postgres:16.0-bookworm
        environment:
            POSTGRES_DB: mydatabase
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
        volumes:
            - tournament_postgres_volume:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U myuser -d mydatabase" ]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: on-failure
