services:
    tournament-nginx:
        networks:
            - transcendence
            - tournament
        build:
            context: nginx
            dockerfile: Dockerfile
        expose:
            - "80"
            - "443"
        ports:
            - "6001:80"
        depends_on:
            - tournament
        volumes:
            - tournament_static_volume:/app/static
            - tournament_media_volume:/app/media
        restart: on-failure

    tournament:
        networks:
            - transcendence
            - tournament
        build:
            context: .
            dockerfile: Dockerfile
        command: sh -c "cp -r /app/tournament /app/src &&
                        cp -r /app/common /app/src/common &&
                        python3 src/manage.py makemigrations &&
                        python3 src/manage.py migrate &&
                        gunicorn --chdir src/ tournament.wsgi:application -w 4 -b 0.0.0.0:8000"
        volumes:
            - tournament_code:/app/tournament
            - common_code:/app/common
        expose:
            - "8000"
        depends_on:
            - tournament-db
        restart: on-failure

    tournament-db:
        networks:
            - tournament
        image: postgres:16.0-bookworm
        environment:
            POSTGRES_DB: mydatabase
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
        volumes:
            - tournament_postgres_volume:/var/lib/postgresql/data
        restart: on-failure
