# Generated by Django 4.2.7 on 2024-02-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_notification_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
