services:
    notification:
        networks:
            - transcendence
            - notification
        build:
            context: .
            dockerfile: Dockerfile
        
          
        command: sh -c "cp -r /app/notification /app/src &&
                        cp /app/notification/.env /app/src/.env &&
                        rm -rf /app/src/common &&
                        cp -r /app/common /app/src/common &&
                        python3 src/manage.py makemigrations &&
                        python3 src/manage.py migrate &&
                        cd /app/src &&
                        daphne -e ssl:443:privateKey=/app/ssl/private.key:certKey=/app/ssl/certificate.crt notification.asgi:application"
        volumes:
            - notification_code:/app/notification
            - common_code:/app/common
            - ssl_certs:/app/ssl
        ports:
            - "6005:443"
        healthcheck:
          test: [ "CMD-SHELL", "curl -kf https://localhost/health/" ]
          interval: 5s
          timeout: 5s
          retries: 60
        restart: on-failure

    notification-db:
        networks:
            - notification
        build:
          context: postgres
          dockerfile: Dockerfile
        environment:
            POSTGRES_DB: $NOTIFICATION_DB_NAME
            POSTGRES_USER: $NOTIFICATION_DB_USER
            POSTGRES_PASSWORD: $NOTIFICATION_DB_PASSWORD
        volumes:
            - notification_postgres_volume:/var/lib/postgresql/data
        healthcheck:
          test: ["CMD-SHELL", "healthcheck.sh"]
          interval: 5s
          timeout: 5s
          retries: 60
        restart: on-failure
