services:
    user-stats-nginx:
        networks:
            - transcendence
            - user_stats
        build:
            context: nginx
            dockerfile: Dockerfile
        expose:
            - "443"
        ports:
            - "6003:443"
        volumes:
            - user_stats_static_volume:/app/static
            - user_stats_media_volume:/app/media
            - ssl_certs:/etc/nginx/ssl
        healthcheck:
            test: [ "CMD-SHELL", "curl -kf https://localhost/health/" ]
            interval: 5s
            timeout: 5s
            retries: 12
        depends_on:
            user-stats:
                condition: service_healthy
        restart: on-failure

    user-stats:
        networks:
            - transcendence
            - user_stats
        build:
            context: .
            dockerfile: Dockerfile
        command: sh -c "cp -r /app/user_stats /app/src &&
                        cp -r /app/common /app/src/common &&
                        python3 src/manage.py makemigrations &&
                        python3 src/manage.py migrate &&
                        gunicorn -c /app/gunicorn.conf.py"
        volumes:
            - user_stats_code:/app/user_stats
            - common_code:/app/common
            - ssl_certs:/app/ssl
        expose:
            - "8000"
        healthcheck:
            test: [ "CMD-SHELL", "curl -kf https://localhost:8000/health/" ]
            interval: 5s
            timeout: 5s
            retries: 12
        depends_on:
            user-stats-db:
                condition: service_healthy
        restart: on-failure

    user-stats-db:
        networks:
            - user_stats
        image: postgres:16.0-bookworm
        environment:
            POSTGRES_DB: mydatabase
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
        volumes:
            - user_stats_postgres_volume:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U myuser" ]
            interval: 5s
            timeout: 5s
            retries: 12
        restart: on-failure
