services:
    user-stats-nginx:
        networks:
            - transcendence
            - user_stats
        build:
            context: nginx
            dockerfile: Dockerfile
        expose:
            - "443"
        ports:
            - "6003:443"
        volumes:
            - ssl_certs:/etc/nginx/ssl
        healthcheck:
            test: [ "CMD-SHELL", "curl -kf https://localhost/health/" ]
            interval: 5s
            timeout: 5s
            retries: 60
        restart: on-failure

    user-stats:
        networks:
            - transcendence
            - user_stats
        build:
            context: .
            dockerfile: Dockerfile
        command: sh -c "cp -r /app/user_stats /app/src &&
                        cp /app/user_stats/.env /app/src/.env &&
                        rm -rf /app/src/common &&
                        cp -r /app/common /app/src/common &&
                        pip install --root-user-action=ignore --no-cache-dir -r /app/src/common/docker/requirements.txt &&
                        python3 src/manage.py makemigrations &&
                        python3 src/manage.py migrate &&
                        gunicorn -c /app/gunicorn.conf.py"
        volumes:
            - user_stats_code:/app/user_stats
            - common_code:/app/common
            - ssl_certs:/app/ssl
        expose:
            - "8000"
        healthcheck:
            test: [ "CMD-SHELL", "curl -kf https://localhost:8000/health/" ]
            interval: 5s
            timeout: 5s
            retries: 60
        restart: on-failure

    user-stats-db:
        networks:
            - user_stats
        build:
            context: postgres
            dockerfile: Dockerfile
        env_file:
            - path: ../src/.env
        volumes:
            - user_stats_postgres_volume:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "sh check_health.sh" ]
            interval: 5s
            timeout: 5s
            retries: 60
        restart: on-failure
