services:
    user-management-nginx:
        networks:
            - transcendence
            - user_management
        build:
            context: nginx
            dockerfile: Dockerfile
        expose:
            - "443"
        ports:
            - "6002:443"
        volumes:
            - ssl_certs:/etc/nginx/ssl
        healthcheck:
            test: [ "CMD-SHELL", "curl -kf https://localhost/health/" ]
            interval: 5s
            timeout: 5s
            retries: 60
        restart: on-failure


    user-management:
        networks:
            - transcendence
            - user_management
        build:
            context: .
            dockerfile: Dockerfile
        command: sh -c "cp -r /app/user_management/* /app/src &&
                        cp /app/user_management/.env /app/src/.env &&
                        rm -rf /app/src/common &&
                        cp -r /app/common /app/src/common &&
                        pip install --root-user-action=ignore --no-cache-dir -r /app/src/common/docker/requirements.txt &&
                        python3 src/manage.py makemigrations &&
                        python3 src/manage.py migrate &&
                        gunicorn -c /app/gunicorn.conf.py"
        volumes:
            - user_management_code:/app/user_management
            - user_management_media_volume:/app/src/media
            - common_code:/app/common
            - ssl_certs:/app/ssl
        expose:
            - "8000"
        healthcheck:
            test: [ "CMD-SHELL", "curl -kf https://localhost:8000/health/" ]
            interval: 5s
            timeout: 5s
            retries: 60
        restart: on-failure


    user-management-db:
        networks:
            - user_management
        build:
            context: postgres
            dockerfile: Dockerfile
        env_file:
            - path: ../src/.env
        volumes:
            - user_management_postgres_volume:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "sh check_health.sh" ]
            interval: 5s
            timeout: 5s
            retries: 60
        restart: on-failure
