name: Matchmaking Tests

on:
    push:
        branches:
            - main
            - dev
            - matchmaking
    pull_request:
        branches:
            - main
            - dev
            - matchmaking

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8
                  pip install isort
                  pip install -r matchmaking/docker/requirements.txt

            - name: Run PEP8 check
              working-directory: matchmaking/src/
              run: |
                  flake8 . --max-line-length=120 --exclude=migrations

            - name: Check imports
              working-directory: matchmaking/src/
              run: |
                  isort . --check-only

            - name: Run unit tests
              working-directory: matchmaking/
              run: |
                  python -m unittest test/test.py
