name: Pong Server Tests

on:
    push:
        branches:
            - main
            - dev
            - pong-game
    pull_request:
        branches:
            - main
            - dev
            - pong-game

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12'

            - name: Install dependencies
              run: |
                  pip3 install --upgrade pip
                  pip3 install flake8
                  pip3 install isort
                  pip3 install -r pong_server/docker/requirements.txt

            - name: Copy shared files
              run: |
                  cp -r pong_server/src/shared_code pong_server/src/game_creator/shared_code
                  cp -r pong_server/src/shared_code pong_server/src/game_server/shared_code

            - name: Run unit tests game creator
              working-directory: pong_server/src/
              run: |
                  export PONG_GAME_SERVERS_MIN_PORT=42200
                  export PONG_GAME_SERVERS_MAX_PORT=42210
                  export GAME_SERVER_PATH=`pwd`/game_server/

                  cd game_creator
                  python3 manage.py test

            - name: Run PEP8 check
              working-directory: pong_server/
              run: |
                  flake8 . --max-line-length=95

            - name: Check imports in game_creator
              working-directory: pong_server/src/game_creator/
              run: |
                  isort . --check-only

            - name: Check imports in game_server
              working-directory: pong_server/src/game_server/
              run: |
                  isort . --check-only

            - name: Check imports in shared_code
              working-directory: pong_server/src/shared_code/
              run: |
                  isort . --check-only

            - name: Check imports in test
              working-directory: pong_server/test/
              run: |
                  isort . --check-only
