name: Pong Server Tests

on:
    push:
        branches:
            - main
            - dev
            - basic-pong
            - pong-game
    pull_request:
        branches:
            - main
            - dev
            - basic-pong
            - pong-game

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12'

            - name: Install dependencies
              run: |
                  pip3 install --upgrade pip
                  pip3 install flake8
                  pip3 install isort
                  pip3 install -r pong_server/docker/requirements.txt

            - name: Run unit tests
              working-directory: pong_server/
              run: |
                  python3 -m unittest discover test

            - name: Run PEP8 check
              working-directory: pong_server/
              run: |
                  flake8 . --max-line-length=95

            - name: Check imports in src
              working-directory: pong_server/src/
              run: |
                  isort . --check-only

            - name: Check imports in test
              working-directory: pong_server/test/
              run: |
                  isort . --check-only
