name: Update Deployment

on:
  push:
    branches:
      - main

jobs:
  update-deployment:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install paramiko

    - name: Update
      working-directory: .github/
      env:
        SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        PROJECT_DIR_NAME: ${{ secrets.PROJECT_DIR_NAME }}
      run: |
        python update_deployment.py
